[package]
name = "xpdash-client"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
xpdash-core = { path = "../xpdash-core" }
tokio.workspace = true
log.workspace = true
env_logger.workspace = true
ringbuf.workspace = true
cpal.workspace = true
lz4_flex.workspace = true
socket2.workspace = true
egui.workspace = true
eframe.workspace = true
parking_lot = "0.12"
bytemuck = { version = "1.25", features = ["extern_crate_alloc"] }
